-- Script Oracle para crear la tabla SOCIO, una secuencia y trigger para NRO_SOCIO
-- Adaptado desde la clase Java Socio.java

-- Secuencia para generar NRO_SOCIO
CREATE SEQUENCE SEQ_SOCIO
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- Tabla SOCIO
CREATE TABLE SOCIO (
  NRO_SOCIO         NUMBER(19)          PRIMARY KEY,
  NUMRUN            NUMBER(10),
  DVRUN             NUMBER(3),
  PNOMBRE           VARCHAR2(100),
  SNOMBRE           VARCHAR2(100),
  APPATERNO         VARCHAR2(100),
  APMATERNO         VARCHAR2(100),
  FOTO              BLOB,
  FECHA_NACIMIENTO  VARCHAR2(50),
  FECHA_INSCRIPCION DATE,
  CORREO            VARCHAR2(255),
  FONO_CONTACTO     NUMBER(15),
  DIRECCION         VARCHAR2(255),
  COD_REGION        VARCHAR2(50),
  COD_PROVINCIA     VARCHAR2(50),
  COD_COMUNA        VARCHAR2(50),
  COD_PROF_OFIC     VARCHAR2(50),
  COD_TIPO_SOCIO    NUMBER(10)
);

-- Trigger para poblar NRO_SOCIO desde la secuencia
CREATE OR REPLACE TRIGGER TRG_SOCIO_BI
BEFORE INSERT ON SOCIO
FOR EACH ROW
BEGIN
  IF :NEW.NRO_SOCIO IS NULL THEN
    SELECT SEQ_SOCIO.NEXTVAL INTO :NEW.NRO_SOCIO FROM DUAL;
  END IF;
END;
/

-- Índices opcionales
CREATE INDEX IDX_SOCIO_NUMRUN ON SOCIO(NUMRUN);
CREATE INDEX IDX_SOCIO_APELLIDOS ON SOCIO(APPATERNO, APMATERNO);
